#!/usr/bin/env bash
# scripts/utils/check-backend-fixture-drift.sh — the bash half of the issue #203
# drift gate.
#
# The broker/worker request shapes have ONE owner: the `agentkeys-backend-client`
# crate + `agentkeys-types`. Rust callers (MCP `HttpBackend`, daemon `ui_bridge`)
# share those serde types, so a Rust-side drift is a COMPILE error. But the
# harness still hand-rolls a few cap-mint / worker bodies with `jq -n '{...}'`
# (real-path probes + negative/HTTP-assertion tests). This gate makes a drifted
# bash body a CI failure too.
#
# A hand-rolled body that is SUPPOSED to match a canonical shape carries an
# annotation comment on the line(s) just above it:
#
#     # @backend-fixture: cap_mint_request
#     -d "$(jq -n --arg o "$O" … '{operator_omni:$o, actor_omni:$o, service:$s,
#            device_key_hash:$d, ttl_seconds:300}')"
#
# The gate finds each annotation, extracts the FIRST brace-balanced object
# literal after it, and diffs its top-level key-set against the crate-emitted
# fixture (e2e/fixtures/backend-protocol/<name>.json, regenerated by
# `cargo run -p agentkeys-backend-client --bin dump-protocol-fixtures`). A body
# that adds `evm_address`, renames `actor_omni`, or drops `device_key_hash` then
# fails here instead of surfacing as a confusing runtime 4xx (the #200 bug
# class).
#
# Annotation (not blanket auto-scan) is deliberate: the harness is full of OTHER
# JSON (chain extrinsics, audit events, deliberately-malformed negative-test
# payloads) that share field names — those must NOT be forced to match. You opt
# a body IN when it is meant to mirror the wire shape. The AGENTS.md rule
# ("never re-type a cap/worker body in bash without tying it to the fixture")
# is what keeps new hand-rolls annotated.
#
# Exit 0 = no drift; exit 1 = drift (prints file:line + the diff); exit 2 = setup
# error (missing jq / fixtures).
#
#   bash scripts/utils/check-backend-fixture-drift.sh
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
FIX_DIR="$REPO_ROOT/e2e/fixtures/backend-protocol"
SCAN_DIR="$REPO_ROOT/e2e"

c() { [ -t 1 ] && printf '\033[%sm%s\033[0m' "$1" "$2" || printf '%s' "$2"; }
ok()   { printf '  %s %s\n' "$(c '1;32' ok)"   "$1"; }
bad()  { printf '  %s %s\n' "$(c '1;31' fail)" "$1"; }
info() { printf '%s %s\n'   "$(c '1;36' '▸')"  "$1"; }

command -v jq  >/dev/null 2>&1 || { bad "jq not found — required for the fixture gate";  exit 2; }
command -v awk >/dev/null 2>&1 || { bad "awk not found — required for the fixture gate"; exit 2; }
[ -d "$FIX_DIR" ] || { bad "fixture dir missing: $FIX_DIR — run dump-protocol-fixtures"; exit 2; }

# Canonical key-set (sorted CSV) for a fixture, straight from the crate output.
fixture_keys() { jq -r 'keys_unsorted | sort | join(",")' "$FIX_DIR/$1.json" 2>/dev/null; }

# Sorted CSV of top-level keys from a (possibly multi-line) jq object literal.
# Strip to the inside of the outermost braces, drop quotes/spaces, split on
# commas, take the identifier before each key's first colon.
extract_keys() {
  printf '%s' "$1" \
    | sed -E 's/^[^{]*\{//; s/\}[^}]*$//' \
    | tr -d '"' | tr -d ' ' \
    | tr ',' '\n' \
    | sed -E 's/:.*$//' \
    | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \
    | sort -u | paste -sd, -
}

info "canonical shapes (from e2e/fixtures/backend-protocol):"
for fx in cap_mint_request memory_put_body memory_get_body config_put_body config_get_body audit_append_v2; do
  [ -f "$FIX_DIR/$fx.json" ] || { bad "missing fixture $fx.json"; exit 2; }
  printf '    %-18s = %s\n' "$fx" "$(fixture_keys "$fx")"
done

# Emit one `shape<TAB>file<TAB>line<TAB>literal` record per annotation: the first
# brace-balanced object literal following each `# @backend-fixture: <shape>`.
emit_records() {
  grep -rl --include='*.sh' '@backend-fixture:' "$SCAN_DIR" 2>/dev/null | while IFS= read -r f; do
    awk '
      /@backend-fixture:/ {
        s=$0; sub(/.*@backend-fixture:[ \t]*/,"",s); sub(/[^A-Za-z0-9_].*/,"",s)
        shape=s; cap=1; depth=0; started=0; rec=""; aline=FNR; next
      }
      cap==1 {
        n=length($0)
        for(i=1;i<=n;i++){
          ch=substr($0,i,1)
          if(ch=="{"){depth++; started=1}
          if(started) rec=rec ch
          if(ch=="}"){depth--; if(depth==0 && started){print shape "\t" FILENAME "\t" aline "\t" rec; cap=0; break}}
        }
        if(cap==1 && FNR-aline>8){cap=0}   # give up after 8 lines (no literal found)
        next
      }
    ' "$f"
  done
}

fails=0
checked=0
missing=0
echo
info "checking annotated cap/worker bodies under ${SCAN_DIR}..."
while IFS=$'\t' read -r shape file aline literal; do
  [ -n "$shape" ] || continue
  rel="${file#"$REPO_ROOT"/}"
  want="$(fixture_keys "$shape")"
  if [ -z "$want" ]; then
    bad "$rel:$aline → unknown shape '$shape' (no fixture $shape.json)"
    missing=$((missing + 1)); continue
  fi
  got="$(extract_keys "$literal")"
  checked=$((checked + 1))
  if [ "$got" = "$want" ]; then
    ok "$rel:$aline → $shape"
  else
    bad "$rel:$aline → $shape DRIFT"
    printf '       want: %s\n       got:  %s\n' "$want" "$got"
    fails=$((fails + 1))
  fi
done < <(emit_records)

# ── Pass 2: no UNANNOTATED canonical-shaped body (issue #203 — Codex follow-up) ──
# Pass 1 only visits ANNOTATED bodies, so a hand-rolled canonical body with no
# annotation is silently ungated — the exact miss Codex found (an unannotated
# memory-get `{cap, namespace}` readback in suite-4-memory-plant.sh). This pass
# scans EVERY single-quoted `jq` object literal and fails any whose key-set
# EXACTLY matches an UNAMBIGUOUS canonical fixture but carries no
# `# @backend-fixture:` annotation on/above it.
#
# Only the four UNAMBIGUOUS shapes auto-detect here. Deliberately EXCLUDED:
#   - `config_put_body` (`{cap, plaintext_b64}`) and `config_get_body` (`{cap}`)
#     — these are key-set-identical to the cred-worker store/fetch bodies, so a
#     `{cap}` literal can't be classified config-vs-cred by shape alone. Config
#     bodies are gated via PASS-1 annotation (explicit `@backend-fixture:
#     config_*`), never auto-detected here (auto-detect would false-positive on
#     every cred `{cap}` / `{cap, plaintext_b64}`).
#   - the ttl-omitted 4-key cap variant (broker `CapRequest.ttl_seconds` is
#     `#[serde(default)]`) — 4 keys, never equals the 5-key `cap_mint_request`.
# So exact-match against ONLY these four stays false-positive-free.
CAP_KEYS="$(fixture_keys cap_mint_request)"
PUT_KEYS="$(fixture_keys memory_put_body)"
GET_KEYS="$(fixture_keys memory_get_body)"
AUDIT_KEYS="$(fixture_keys audit_append_v2)"
canonical_shape() { case "$1" in
  "$CAP_KEYS")   echo cap_mint_request ;;
  "$PUT_KEYS")   echo memory_put_body  ;;
  "$GET_KEYS")   echo memory_get_body  ;;
  "$AUDIT_KEYS") echo audit_append_v2  ;;
  *) echo "" ;;   # config_put/config_get intentionally absent — see comment above
esac; }

# Emit `file<TAB>line<TAB>annotated(0|1)<TAB>literal` for every single-quoted
# `'{...}'` jq object literal (brace-balanced, multi-line aware). `annotated`=1
# when an unconsumed `@backend-fixture:` comment sits within the 8 lines above —
# the same one-annotation-covers-the-next-literal semantics as pass 1.
emit_all_jq_literals() {
  grep -rl --include='*.sh' 'jq ' "$SCAN_DIR" 2>/dev/null | while IFS= read -r f; do
    awk -v SQ="'" '
      BEGIN { pend = 0; annL = -100 }
      /@backend-fixture:/ { pend = 1; annL = FNR }
      {
        s = $0; i = 1; L = length(s)
        while (i <= L) {
          ch = substr(s, i, 1)
          if (!inlit) {
            if (ch == SQ && substr(s, i + 1, 1) == "{") { inlit = 1; depth = 0; rec = ""; startL = FNR; i++; continue }
          } else {
            if (ch == "{") depth++
            if (depth > 0) rec = rec ch
            if (ch == "}") {
              depth--
              if (depth == 0) {
                ann = (pend && startL - annL >= 0 && startL - annL <= 8) ? 1 : 0
                if (ann) pend = 0
                g = rec; gsub(/[\t ]/, "", g)
                print FILENAME "\t" startL "\t" ann "\t" g
                inlit = 0
              }
            }
          }
          i++
        }
      }
    ' "$f"
  done
}

unannotated=0
while IFS=$'\t' read -r file aline annotated literal; do
  [ -n "$literal" ] || continue
  keys="$(extract_keys "$literal")"
  shape="$(canonical_shape "$keys")"
  [ -z "$shape" ] && continue        # not a canonical shape — ignore (cred bodies, 4-key cap, …)
  [ "$annotated" = "1" ] && continue # already annotated → validated by pass 1
  rel="${file#"$REPO_ROOT"/}"
  bad "$rel:$aline → UNANNOTATED canonical body (matches $shape) — add '# @backend-fixture: $shape' on the line above it, else the gate can never catch its drift"
  unannotated=$((unannotated + 1))
done < <(emit_all_jq_literals)

echo
if [ "$checked" -eq 0 ] && [ "$missing" -eq 0 ] && [ "$unannotated" -eq 0 ]; then
  info "no @backend-fixture-annotated bodies found under $SCAN_DIR"
  info "(real-path steps drive the shared client; annotate any hand-rolled cap/worker body to gate it)"
fi
if [ "$fails" -gt 0 ] || [ "$missing" -gt 0 ] || [ "$unannotated" -gt 0 ]; then
  bad "$((fails + missing + unannotated)) issue(s): $fails drifted + $missing unknown-shape + $unannotated unannotated-canonical — fix the bash body / annotate it, or if the protocol changed regenerate the fixtures (cargo run -p agentkeys-backend-client --bin dump-protocol-fixtures) + update the Rust types"
  exit 1
fi
ok "no drift — $checked annotated bod(y/ies) match the canonical shapes; no unannotated canonical bodies"
